name: tinyguard
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bluetooth_serial: ^0.4.0
  flutter_mjpeg: ^2.0.4
  flutter_hooks: ^0.18.6
  get: ^4.6.5
  card_swiper: ^3.0.1
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  dio: ^5.3.3
  shared_preferences: ^2.2.2
  flutter_screenutil: ^5.9.0
  socket_io_client: ^2.0.3+1
  flutter_svg: ^2.0.9
  get_it: ^7.6.4
  device_info_plus: ^9.1.1
  flutter_background_service: ^5.0.5
  flutter_background_service_android: ^6.2.2
  flutter_local_notifications: ^16.2.0
  audioplayers: ^5.2.1  
  intl: ^0.18.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/
    - assets/icons/
    - assets/audio/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Black.ttf
          weight: 900
        - asset: assets/fonts/Roboto-Black.ttf
          weight: 800
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 600
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Thin.ttf
          weight: 300
    
